### ISSUE TITLE
Deprecated syntax

### ISSUE THREAD

**Issue by nuukular** [eskatos/asadmin#16]
It seems that the plug-in uses a deprecated syntax.
Here is the output I got:

[ASADMIN] Will run the following command: /Users/local/Desktop/glassfish3/bin/asadmin deploy --host localhost --port 10048 --user admin --passwordfile /Users/local/.asadminpass --target target --name appname /Users/local/Projects/application.ear
[ASADMIN] [OUTPUT] Deprecated syntax, instead use:
[ASADMIN] [OUTPUT] asadmin --host localhost --port 10048 --user admin --passwordfile /Users/local/.asadminpass deploy [options] ...

**Comment by eskatos** [comment]
Yes, we use this syntax because it is compatible with Glassfish V2 _and_ V3.
We won't drop V2 support for now but will eventually in the future if it's support in V3 is dismissed.

I close this issue as for now it's a "won't fix".
