### ISSUE TITLE
Add asadmin commands to manage Glassfish V2 realm-file

### ISSUE THREAD

**Issue by csouvignier** [eskatos/asadmin#3]
Add asadmin commands to manage realm-file :
- create-file-user
- delete-file-user
- update-file-user
- list-file-users

**Comment by eskatos** [comment]
Christophe pushed commands to the asadmin-java project in b9d83ab7e74687f06af27f24c551fba556ccaf19

They are not in the asadmin-maven-plugin for now, this will have to be done before closing this issue.
