### ISSUE TITLE
Windows socket error

### ISSUE THREAD

**Issue by JF9** [eskatos/asadmin#7]
This does not appear in the 0.8 we have.

Environment: Windows Server 2008 SP2, JDK1.6b24, glassfish 3.1

Under Windows running Runtime.getRuntime().exec( windowsCommand, env ); when env is an empty array seems to loose the inherited environment and as such gives rise to:

java.net.SocketException: Unrecognized Windows Sockets error: 10106: create

from asadmin.

If I use Runtime.getRuntime().exec( windowsCommand) without the env when there are no env vars then everything works fine.

Alternatively I can set SystemRoot in the environment for Runtime.getRuntime().exec( windowsCommand, env) . For example by overriding AbstractAsadminMojo or a subclass;

```
public Map<String, String> getEnvironmentVariables()
{
    if ( SystemUtils.IS_OS_WINDOWS ) {
        String systemRoot = System.getenv("SystemRoot");
        HashMap<String, String> map = new HashMap<String, String>();
        map.put("SystemRoot", systemRoot);
        return map;
    }
    else
        return Collections.emptyMap();
}
```

see 
 http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6256268

Thanks for the MOJOS.....

**Comment by eskatos** [comment]
Hey JF9,

Could changing Asadmin#run() method only do the trick ?

Around line 129 replace :

<pre>proc = Runtime.getRuntime().exec( windowsCommand, env );</pre>


by :

<pre>
if ( env.length > 0 ) {
    proc = Runtime.getRuntime().exec( windowsCommand, env );
} else {
    proc = Runtime.getRuntime().exec( windowsCommand );
}
</pre>


What do you think ? Could you test it ?

/Paul

**Comment by JF9** [comment]
Yes it works fine. I think is preferable to the explicit setting of SystemRoot and is what I originally implemented here, I just provided the other approach in case others needed to pass any env stuff...

**Comment by eskatos** [comment]
Ok I'll push that fix asap.
